### PR TITLE
Removed Duplicate Tech Stack section

### LINKED ISSUE #56: Tech Stack written twice in README.md
Refer this:
image

I can fix this as a part of DWoC. Please assign this to me!

### PR DESCRIPTION
**Pull request by vismitap**
Fixed #56

### CODE REVIEW

**Comment by vismitap** [comment]
Hey! I noticed now that there is duplicate contributors heading also in README.md while scrolling down! I can fix that too!

**Comment by sanjay270899** [comment]
@vismitap Can you fix that also in this same PR?

**Comment by vismitap** [comment]
> @vismitap Can you fix that also in this same PR?

Okie sure! I thought I will have to create a new issue for that. I will make a new commit referring to the same issue!👍

**Comment by sanjay270899** [comment]
@vismitap You have already made an Issue. So leave it. Make a new PR. But from next time, try to do in same PR, if issues are similar.

**Comment by vismitap** [comment]
> @vismitap You have already made an Issue. So leave it. Make a new PR. But from next time, try to do in same PR, if issues are similar.

Yeah sorry, noticed the issue after raising a PR in a hurry. I will go through the whole file and make necessary changes! Thanks for assigning!

**Pull request merged**
